spring.application.name=auth-service

server.port=8081

# Database URL (Notice the 'jdbc:' prefix and the unpooled endpoint)
spring.datasource.url=${DB_URL}

# Credentials
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# Driver Specification
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate / JPA Settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
