eureka:
  client:
    enabled: false

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: http://auth-service:8081
              predicates:
                - Path=/api/v1/auth/**, /api/v1/riders/**, /api/v1/drivers/**
              filters:
                - StripPrefix=2

            - id: location-service
              uri: http://location-service:8082
              predicates:
                - Path=/api/v1/locations/**
              filters:
                - StripPrefix=2

            - id: ride-service
              uri: http://ride-service:8083
              predicates:
                - Path=/api/v1/rides/**
              filters:
                - StripPrefix=2