apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret-example
  namespace: onride
type: Opaque
stringData:
  DB_URL: "jdbc:postgresql://your-neon-host/neondb?sslmode=require"
  DB_USER: "changeme"
  DB_PASSWORD: "changeme"
  JWT_SECRET: "changeme"
