apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: onride
  labels:
    app: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      enableServiceLinks: false
      containers:
        - name: auth-service
          image: docker.io/allstar98k/onride-auth-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: MANAGEMENT_OPENTELEMETRY_TRACING_EXPORT_OTLP_ENDPOINT
              value: "http://jaeger:4318/v1/traces"
            - name: EUREKA_CLIENT_ENABLED
              value: "false"
            - name: SERVER_FORWARD_HEADERS_STRATEGY
              value: "framework"
            - name: JWT_EXPIRATION_SECONDS
              value: "900"
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: auth-service-secret
                  key: DB_URL
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: auth-service-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-service-secret
                  key: DB_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-service-secret
                  key: JWT_SECRET
          resources:
            requests:
              memory: "384Mi"
              cpu: "150m"
            limits:
              memory: "512Mi"
              cpu: "400m"

---

apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: onride
spec:
  selector:
    app: auth-service
  ports:
    - port: 8081
      targetPort: 8081