spring.application.name=discovery-service

server.port=8761

# This IS the registry — it shouldn't register with or fetch from itself
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# OpenTelemetry
management.opentelemetry.tracing.export.otlp.endpoint=http://localhost:4318/v1/traces
management.tracing.sampling.probability=1.0