spring.application.name=matching-service

server.port=8084

# Redis
spring.data.redis.url=${REDIS_URL:redis://localhost:6379}
spring.data.redis.timeout=2s
spring.data.redis.connect-timeout=3s

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# gRPC
grpc.client.location-service.address=discovery:///location-service
grpc.client.location-service.negotiation-type=plaintext
grpc.server.port=9096
eureka.instance.metadata-map.gRPC_port=${grpc.server.port}

# Kafka
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.consumer.group-id=matching-service
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=io.confluent.kafka.serializers.KafkaAvroDeserializer
spring.kafka.consumer.properties.specific.avro.reader=true
spring.kafka.properties.schema.registry.url=${SCHEMA_REGISTRY_URL:http://localhost:8085}
kafka.topic.ride-requested-topic=ride-requested-topic

# Matching
onride.matching.average-speed-kmph=25
onride.matching.batch-interval-ms=3000
onride.matching.offer-window-seconds=10
